org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=littletreat
mod_name=Little Treat
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.odder.littletreat

attributes_version=0.8.2+1.21
jei_version=19.42.0.385